// Frontend/src/pages/Home.tsx
import React, { ReactElement } from 'react';

function Home(): ReactElement {
  return (
    <div className="content-page flex flex-col items-center">
      <h1 className="mt-4 text-xl">
        SYMBIOTE - An application-layer tool that allows iot devices to
        communicate automatically
      </h1>

      <p className="mt-8 px-2 md:w">
        SYMBIOTE is a composed word that is related to IoT, symbiotic bonds
        (biology) and Bots (software). Embedded devices are connected to the
        world wide web by using internet protocols. So called Internet-of-Things
        (IoT) devices already create value. Application examples include
        monitoring capabilities or predictive maintenance scenarios. However,
        even more value is hidden when multiple IoT devices are composed with
        open interfaces that chat can be access by third-parties. Hence,
        SYMBIOTE breaks down IoT application silos to enable symbiotic bonds
        between open IoT devices. In the short-term, the tool supports software
        engineers to generate software adapters easily. In the long-term, the
        tool can work without human intervention by automating the generation
        process completely - just like a bot. This is mainly achieved by using
        reasoning principles (e.g. transitive relations) from logical artificial
        intelligence. Hence, SYMBIOTE takes over repetitive software adapter
        implementation tasks such that software engineers can focus on the
        important stuff.
      </p>
    </div>
  );
}

export default Home;

// Frontend/src/app/views/home/home.component.ts
import { CdkOverlayOrigin, Overlay, OverlayRef } from '@angular/cdk/overlay';
import { ComponentPortal, PortalInjector } from '@angular/cdk/portal';
import { Component, Injector, OnInit, ViewChild } from '@angular/core';
import { USER_INPUT_ACCOUNTCARD, AccountCardComponent } from '~/app/components/account-card/account-card.component';
import { AuthenticationService } from '~/app/services/auth/authentication.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent {

  @ViewChild('accountCardOrigin') accountCardOrigin!: CdkOverlayOrigin;

  constructor(
    private overlay: Overlay,
    private injector: Injector,
    public identificationService: AuthenticationService
  ) { }

  async openAccountCard(event: MouseEvent) {
    if (this.identificationService.AuthUser) {
      let overlayRef = this.overlay.create({
        hasBackdrop: true,
        backdropClass: "transparent-backdrop",
        disposeOnNavigation: false,
        scrollStrategy: this.overlay.scrollStrategies.noop(),
        positionStrategy: this.overlay.position().connectedTo(this.accountCardOrigin.elementRef, { originX: 'end', originY: 'bottom' }, { overlayX: 'end', overlayY: 'top' }),
      });

      let injectionData = new WeakMap();
      injectionData.set(USER_INPUT_ACCOUNTCARD, this.identificationService.AuthUser);
      injectionData.set(OverlayRef, overlayRef);
      let accountCardPortal = new ComponentPortal(AccountCardComponent, null, new PortalInjector(this.injector, injectionData));

      overlayRef.attach(accountCardPortal);
      overlayRef.backdropClick().subscribe(() => overlayRef.dispose());
    }
  }
}

<mat-toolbar class="toolbar" color="primary">
  <div class="row flex-grow-1">

    <div class="col-4">
    </div>

    <div class="col-4 d-flex justify-content-center">
      SYMBIOTE - An application-layer tool that allows iot devices to communicate automatically
    </div>

    <div class="col-4">
      <div *ngIf="identificationService.AuthUser as user" class="float-right">
        <button cdkOverlayOrigin #accountCardOrigin="cdkOverlayOrigin" mat-mini-fab class="float-right"
          (click)="openAccountCard($event)">
          <mat-icon>person</mat-icon>
        </button>
      </div>
    </div>

  </div>
</mat-toolbar>

<ng-container *ngIf="!routerOutlet.isActivated">
  <div class="container-fluid px-5 py-4">
    <div class="row">
      <div class="col d-flex justify-content-center">
        <h1>Please select the component model you are using</h1>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col d-flex flex-wrap justify-content-center">
        <button mat-raised-button color="primary" class="p-3" [routerLink]="['/openapi']">
          <h3 class="mb-2">OpenAPI</h3>
          <span>A description standard for RESTful APIs (e.g. HTTTP)</span>
        </button>
      </div>
      <div class="col d-flex justify-content-center">
        <button mat-raised-button color="primary" class="p-3" [routerLink]="['/asyncapi']">
          <h3 class="mb-2">AsyncAPI</h3>
          <span>A description standard for Event-driven Architectures (e.g. MQTT)</span>
        </button>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col d-flex justify-content-center">
        <mat-card style="width: 50%; text-align: justify">
          <mat-card-title>About SYMBIOTE</mat-card-title>
          <mat-card-content>
            SYMBIOTE is a composed word that is related to IoT, symbiotic bonds (biology) and Bots (software). Embedded
            devices are connected to the world wide web
            by using internet protocols. So called Internet-of-Things (IoT) devices already create value. Application
            examples include monitoring capabilities or predictive
            maintenance scenarios. However, even more value is hidden when multiple IoT devices are architected with
            open interfaces that chat can be access by
            third-parties. Hence, SYMBIOTE breaks down IoT application silos to enable symbiotic bonds between open IoT
            devices. In the short-term, the tool
            supports software engineers to generate software adapters easily. In the long-term, the tool can work
            without human intervention by automating the generation
            process completely - just like a bot. This is mainly achieved by using reasoning principles (e.g. transitive
            relations) from
            logical artificial intelligence. Hence, SYMBIOTE takes over repetitive software adapter implementation tasks
            such that software engineers can focus on
            the important stuff.
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>
</ng-container>

<router-outlet #routerOutlet="outlet" class="p-4"></router-outlet>
